package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Momika808/platformctl-gitops-golden-path/internal/appspec"
	"gopkg.in/yaml.v3"
)

const generatedHeader = "# GENERATED BY scripts/platform-render.sh. DO NOT EDIT."

var appPathPattern = regexp.MustCompile(`clusters/homelab/([^/]+)/apps/([^/]+)/app\.yaml$`)

func runRender(args []string) error {
	fsRender := flag.NewFlagSet("render", flag.ContinueOnError)
	fsRender.SetOutput(os.Stderr)

	var (
		all          bool
		appFile      string
		repoRoot     string
		skipValidate bool
	)

	fsRender.BoolVar(&all, "all", false, "render all app specs")
	fsRender.StringVar(&appFile, "app", "", "render single app spec")
	fsRender.StringVar(&repoRoot, "repo-root", "", "override repository root")
	fsRender.BoolVar(&skipValidate, "skip-validate", false, "skip schema validation")

	if err := fsRender.Parse(args); err != nil {
		return err
	}

	if (all && appFile != "") || (!all && appFile == "") {
		return errors.New("use exactly one mode: --all or --app <path>")
	}

	root, err := resolveRepoRoot(repoRoot)
	if err != nil {
		return err
	}

	var files []string
	if all {
		files, err = findAllAppSpecs(root)
		if err != nil {
			return err
		}
	} else {
		file := appFile
		if !filepath.IsAbs(file) {
			file = filepath.Join(root, file)
		}
		files = []string{file}
	}

	if len(files) == 0 {
		fmt.Println("No ServiceApp files found (clusters/homelab/*/apps/*/app.yaml).")
		return nil
	}

	for _, file := range files {
		spec, err := appspec.Load(file)
		if err != nil {
			return fmt.Errorf("%s: %w", relPath(root, file), err)
		}

		if !skipValidate {
			issues := appspec.Validate(spec, file)
			if len(issues) > 0 {
				var parts []string
				for _, issue := range issues {
					parts = append(parts, issue.Error())
				}
				return fmt.Errorf("%s: %s", relPath(root, file), strings.Join(parts, "; "))
			}
		}

		if err := renderOne(root, file, spec); err != nil {
			return err
		}
	}

	fmt.Println("Render completed.")
	return nil
}

func renderOne(repoRoot, appFile string, spec *appspec.ServiceApp) error {
	matches := appPathPattern.FindStringSubmatch(filepath.ToSlash(appFile))
	if len(matches) != 3 {
		return fmt.Errorf("%s: unexpected app path format", relPath(repoRoot, appFile))
	}
	pathLayer := matches[1]
	pathName := matches[2]

	if spec.Spec.Layer != pathLayer {
		return fmt.Errorf("%s: spec.layer (%s) must match path layer (%s)", relPath(repoRoot, appFile), spec.Spec.Layer, pathLayer)
	}
	if spec.Metadata.Name != pathName {
		return fmt.Errorf("%s: metadata.name (%s) must match path app name (%s)", relPath(repoRoot, appFile), spec.Metadata.Name, pathName)
	}

	appDir := filepath.Dir(appFile)
	generatedDir := filepath.Join(appDir, "generated")
	if err := os.MkdirAll(generatedDir, 0o755); err != nil {
		return fmt.Errorf("create generated dir: %w", err)
	}

	if err := writeGeneratedValues(repoRoot, appFile, generatedDir, spec); err != nil {
		return err
	}
	if err := writeGeneratedHelmRelease(generatedDir, spec); err != nil {
		return err
	}
	if err := writeGeneratedKustomization(generatedDir, spec); err != nil {
		return err
	}

	if isEnabled(spec.Spec.ImageAutomation.Enabled) {
		if err := writeGeneratedImageRepository(generatedDir, spec); err != nil {
			return err
		}
		if err := writeGeneratedImagePolicy(generatedDir, spec); err != nil {
			return err
		}
		if err := writeGeneratedImageUpdateAutomation(repoRoot, generatedDir, spec); err != nil {
			return err
		}
	} else {
		_ = os.Remove(filepath.Join(generatedDir, "imagerepository.yaml"))
		_ = os.Remove(filepath.Join(generatedDir, "imagepolicy.yaml"))
		_ = os.Remove(filepath.Join(generatedDir, "imageupdateautomation.yaml"))
	}

	appKustomization := filepath.Join(appDir, "kustomization.yaml")
	if _, err := os.Stat(appKustomization); errors.Is(err, os.ErrNotExist) {
		body := "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n  - generated\n"
		if err := writeGeneratedFile(appKustomization, "app.yaml", body); err != nil {
			return err
		}
	}

	fmt.Printf("Rendered %s -> %s\n", relPath(repoRoot, appFile), relPath(repoRoot, generatedDir))
	return nil
}

func writeGeneratedValues(repoRoot, appFile, generatedDir string, spec *appspec.ServiceApp) error {
	doc := makeValuesDoc(spec)
	payload, err := marshalYAMLWithIndent(doc, 2)
	if err != nil {
		return fmt.Errorf("marshal values.yaml: %w", err)
	}

	output := string(payload)
	if spec.Spec.Image.Digest != "" || isEnabled(spec.Spec.ImageAutomation.Enabled) {
		digestLine := fmt.Sprintf("  digest: %q", spec.Spec.Image.Digest)
		if isEnabled(spec.Spec.ImageAutomation.Enabled) {
			marker := fmt.Sprintf(" # {\"$imagepolicy\": \"%s:%s:digest\"}", spec.Spec.Namespace, spec.Metadata.Name)
			digestLine += marker
		}
		re := regexp.MustCompile(`(?m)^\s*digest:.*$`)
		output = re.ReplaceAllLiteralString(output, digestLine)
	}

	target := filepath.Join(generatedDir, "values.yaml")
	return writeGeneratedFile(target, "../app.yaml", output)
}

func writeGeneratedHelmRelease(generatedDir string, spec *appspec.ServiceApp) error {
	type valuesFrom struct {
		Kind      string `yaml:"kind"`
		Name      string `yaml:"name"`
		ValuesKey string `yaml:"valuesKey"`
	}
	type remediation struct {
		Retries              int  `yaml:"retries"`
		RemediateLastFailure bool `yaml:"remediateLastFailure,omitempty"`
	}
	type hrDoc struct {
		APIVersion string `yaml:"apiVersion"`
		Kind       string `yaml:"kind"`
		Metadata   struct {
			Name      string `yaml:"name"`
			Namespace string `yaml:"namespace"`
		} `yaml:"metadata"`
		Spec struct {
			Interval    string `yaml:"interval"`
			Timeout     string `yaml:"timeout"`
			ReleaseName string `yaml:"releaseName"`
			Chart       struct {
				Spec struct {
					Chart     string `yaml:"chart"`
					SourceRef struct {
						Kind      string `yaml:"kind"`
						Name      string `yaml:"name"`
						Namespace string `yaml:"namespace"`
					} `yaml:"sourceRef"`
				} `yaml:"spec"`
			} `yaml:"chart"`
			Install struct {
				Remediation remediation `yaml:"remediation"`
			} `yaml:"install"`
			Upgrade struct {
				Remediation remediation `yaml:"remediation"`
			} `yaml:"upgrade"`
			ValuesFrom []valuesFrom `yaml:"valuesFrom"`
		} `yaml:"spec"`
	}

	var doc hrDoc
	doc.APIVersion = "helm.toolkit.fluxcd.io/v2"
	doc.Kind = "HelmRelease"
	doc.Metadata.Name = spec.Metadata.Name
	doc.Metadata.Namespace = spec.Spec.Namespace
	doc.Spec.Interval = "10m"
	doc.Spec.Timeout = "10m"
	doc.Spec.ReleaseName = spec.Metadata.Name
	doc.Spec.Chart.Spec.Chart = "./clusters/homelab/charts/service-template"
	doc.Spec.Chart.Spec.SourceRef.Kind = "GitRepository"
	doc.Spec.Chart.Spec.SourceRef.Name = "homelab"
	doc.Spec.Chart.Spec.SourceRef.Namespace = "flux-system"
	doc.Spec.Install.Remediation = remediation{Retries: 3}
	doc.Spec.Upgrade.Remediation = remediation{Retries: 3, RemediateLastFailure: true}
	doc.Spec.ValuesFrom = []valuesFrom{
		{Kind: "ConfigMap", Name: fmt.Sprintf("%s-values-generated", spec.Metadata.Name), ValuesKey: "values.yaml"},
	}

	payload, err := marshalYAMLWithIndent(doc, 2)
	if err != nil {
		return fmt.Errorf("marshal helmrelease.yaml: %w", err)
	}
	target := filepath.Join(generatedDir, "helmrelease.yaml")
	return writeGeneratedFile(target, "../app.yaml", string(payload))
}

func writeGeneratedKustomization(generatedDir string, spec *appspec.ServiceApp) error {
	type cmGen struct {
		Name  string   `yaml:"name"`
		Files []string `yaml:"files"`
	}
	type kDoc struct {
		APIVersion         string   `yaml:"apiVersion"`
		Kind               string   `yaml:"kind"`
		Namespace          string   `yaml:"namespace"`
		Resources          []string `yaml:"resources"`
		ConfigMapGenerator []cmGen  `yaml:"configMapGenerator"`
		GeneratorOptions   struct {
			DisableNameSuffixHash bool `yaml:"disableNameSuffixHash"`
			Labels                struct {
				Watch string `yaml:"reconcile.fluxcd.io/watch"`
			} `yaml:"labels"`
		} `yaml:"generatorOptions"`
	}

	doc := kDoc{
		APIVersion: "kustomize.config.k8s.io/v1beta1",
		Kind:       "Kustomization",
		Namespace:  spec.Spec.Namespace,
		Resources:  []string{"helmrelease.yaml"},
		ConfigMapGenerator: []cmGen{
			{Name: fmt.Sprintf("%s-values-generated", spec.Metadata.Name), Files: []string{"values.yaml"}},
		},
	}
	if isEnabled(spec.Spec.ImageAutomation.Enabled) {
		doc.Resources = append(doc.Resources, "imagerepository.yaml", "imagepolicy.yaml", "imageupdateautomation.yaml")
	}
	doc.GeneratorOptions.DisableNameSuffixHash = true
	doc.GeneratorOptions.Labels.Watch = "Enabled"

	payload, err := marshalYAMLWithIndent(doc, 2)
	if err != nil {
		return fmt.Errorf("marshal generated kustomization: %w", err)
	}
	target := filepath.Join(generatedDir, "kustomization.yaml")
	return writeGeneratedFile(target, "../app.yaml", string(payload))
}

func writeGeneratedImageRepository(generatedDir string, spec *appspec.ServiceApp) error {
	interval := defaultString(spec.Spec.ImageAutomation.ImageRepositoryInterval, "5m")
	harborCASecret := defaultString(spec.Spec.ImageAutomation.HarborCASecret, "harbor-oci-ca")
	registrySecret := defaultString(spec.Spec.ImageAutomation.RegistrySecret, "harbor-proxy-robot")
	body := fmt.Sprintf(`apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: %s
  namespace: %s
spec:
  image: %s
  interval: %s
  certSecretRef:
    name: %s
  secretRef:
    name: %s
`, spec.Metadata.Name, spec.Spec.Namespace, spec.Spec.Image.Repository, interval, harborCASecret, registrySecret)

	target := filepath.Join(generatedDir, "imagerepository.yaml")
	return writeGeneratedFile(target, "../app.yaml", body)
}

func writeGeneratedImagePolicy(generatedDir string, spec *appspec.ServiceApp) error {
	pattern := defaultString(spec.Spec.ImageAutomation.TagPattern, "^main$")
	order := defaultString(spec.Spec.ImageAutomation.Order, "asc")
	interval := defaultString(spec.Spec.ImageAutomation.ImagePolicyInterval, "5m")
	body := fmt.Sprintf(`apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: %s
  namespace: %s
spec:
  imageRepositoryRef:
    name: %s
  filterTags:
    pattern: '%s'
  policy:
    alphabetical:
      order: %s
  digestReflectionPolicy: Always
  interval: %s
`, spec.Metadata.Name, spec.Spec.Namespace, spec.Metadata.Name, pattern, order, interval)
	target := filepath.Join(generatedDir, "imagepolicy.yaml")
	return writeGeneratedFile(target, "../app.yaml", body)
}

func writeGeneratedImageUpdateAutomation(repoRoot, generatedDir string, spec *appspec.ServiceApp) error {
	interval := defaultString(spec.Spec.ImageAutomation.ImageAutomationInterval, "5m")
	source := defaultString(spec.Spec.ImageAutomation.GitSource, "homelab-write")
	sourceNs := defaultString(spec.Spec.ImageAutomation.GitNamespace, "flux-system")
	relGenerated := relPath(repoRoot, generatedDir)

	body := fmt.Sprintf(`apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: %s
  namespace: %s
spec:
  interval: %s
  sourceRef:
    kind: GitRepository
    name: %s
    namespace: %s
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(images): update %s digest
    push:
      branch: master
  update:
    path: ./%s
    strategy: Setters
`, spec.Metadata.Name, spec.Spec.Namespace, interval, source, sourceNs, spec.Metadata.Name, relGenerated)

	target := filepath.Join(generatedDir, "imageupdateautomation.yaml")
	return writeGeneratedFile(target, "../app.yaml", body)
}

func writeGeneratedFile(path, sourceRef, body string) error {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("\n")
	buf.WriteString("# Source: ")
	buf.WriteString(sourceRef)
	buf.WriteString("\n")
	buf.WriteString(strings.TrimRight(body, "\n"))
	buf.WriteString("\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func defaultString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

type valuesDoc struct {
	NameOverride                 string                  `yaml:"nameOverride"`
	FullnameOverride             string                  `yaml:"fullnameOverride"`
	ReplicaCount                 int                     `yaml:"replicaCount"`
	Image                        valuesImage             `yaml:"image"`
	ImagePullSecrets             []nameRef               `yaml:"imagePullSecrets"`
	ServiceAccount               valuesServiceAccount    `yaml:"serviceAccount"`
	ContainerPort                int                     `yaml:"containerPort"`
	Service                      valuesService           `yaml:"service"`
	Resources                    valuesResources         `yaml:"resources"`
	Env                          map[string]any          `yaml:"env"`
	SecretEnv                    []appspec.SecretEnvItem `yaml:"secretEnv"`
	Probes                       valuesProbes            `yaml:"probes"`
	AutomountServiceAccountToken bool                    `yaml:"automountServiceAccountToken"`
	EnableServiceLinks           bool                    `yaml:"enableServiceLinks"`
	ServiceMonitor               valuesServiceMonitor    `yaml:"serviceMonitor"`
	HTTPRoute                    *valuesHTTPRoute        `yaml:"httpRoute,omitempty"`
}

type valuesImage struct {
	Repository string `yaml:"repository"`
	Tag        string `yaml:"tag"`
	Digest     string `yaml:"digest,omitempty"`
	PullPolicy string `yaml:"pullPolicy"`
}

type nameRef struct {
	Name string `yaml:"name"`
}

type valuesServiceAccount struct {
	Create bool   `yaml:"create"`
	Name   string `yaml:"name"`
}

type valuesService struct {
	Enabled    bool   `yaml:"enabled"`
	Type       string `yaml:"type"`
	Port       int    `yaml:"port"`
	TargetPort any    `yaml:"targetPort"`
}

type valuesResources struct {
	Requests valuesResourceUnits `yaml:"requests"`
	Limits   valuesResourceUnits `yaml:"limits"`
}

type valuesResourceUnits struct {
	CPU    string `yaml:"cpu,omitempty"`
	Memory string `yaml:"memory,omitempty"`
}

type valuesProbes struct {
	Enabled   bool                 `yaml:"enabled"`
	Path      string               `yaml:"path"`
	Startup   valuesProbeComponent `yaml:"startup"`
	Readiness valuesProbeComponent `yaml:"readiness"`
	Liveness  valuesProbeComponent `yaml:"liveness"`
}

type valuesProbeComponent struct {
	Enabled             bool `yaml:"enabled"`
	InitialDelaySeconds int  `yaml:"initialDelaySeconds"`
	PeriodSeconds       int  `yaml:"periodSeconds"`
	TimeoutSeconds      int  `yaml:"timeoutSeconds"`
	FailureThreshold    int  `yaml:"failureThreshold"`
}

type valuesServiceMonitor struct {
	Enabled bool   `yaml:"enabled"`
	Path    string `yaml:"path"`
}

type valuesHTTPRoute struct {
	Enabled    bool                  `yaml:"enabled"`
	Hostnames  []string              `yaml:"hostnames"`
	ParentRefs []valuesHTTPRouteRef  `yaml:"parentRefs"`
	Rules      []valuesHTTPRouteRule `yaml:"rules"`
}

type valuesHTTPRouteRef struct {
	Name        string `yaml:"name"`
	Namespace   string `yaml:"namespace"`
	SectionName string `yaml:"sectionName"`
}

type valuesHTTPRouteRule struct {
	Matches []valuesHTTPRouteMatch `yaml:"matches"`
}

type valuesHTTPRouteMatch struct {
	Path valuesHTTPRoutePath `yaml:"path"`
}

type valuesHTTPRoutePath struct {
	Type  string `yaml:"type"`
	Value string `yaml:"value"`
}

func makeValuesDoc(spec *appspec.ServiceApp) valuesDoc {
	servicePort := spec.Spec.Service.Port
	containerPort := spec.Spec.ContainerPort
	if containerPort == 0 {
		containerPort = servicePort
	}

	targetPort := spec.Spec.Service.TargetPort
	if targetPort == nil {
		targetPort = servicePort
	}

	replicas := spec.Spec.ReplicaCount
	if replicas <= 0 {
		replicas = 1
	}

	imageTag := defaultString(spec.Spec.Image.Tag, "main")
	imagePullPolicy := defaultString(spec.Spec.Image.PullPolicy, "IfNotPresent")
	serviceType := defaultString(spec.Spec.Service.Type, "ClusterIP")
	healthPath := defaultString(spec.Spec.Health.Path, "/health")
	serviceAccountName := defaultString(spec.Spec.ServiceAccount.Name, "vso-"+spec.Spec.Namespace)
	imagePullSecret := defaultString(spec.Spec.ImagePullSecret, "harbor-proxy-robot")
	monitoringPath := defaultString(spec.Spec.Monitoring.Path, "/metrics")

	env := spec.Spec.Env
	if env == nil {
		env = map[string]any{}
	}
	secretEnv := spec.Spec.SecretEnv
	if secretEnv == nil {
		secretEnv = []appspec.SecretEnvItem{}
	}

	doc := valuesDoc{
		NameOverride:     spec.Metadata.Name,
		FullnameOverride: spec.Metadata.Name,
		ReplicaCount:     replicas,
		Image: valuesImage{
			Repository: spec.Spec.Image.Repository,
			Tag:        imageTag,
			PullPolicy: imagePullPolicy,
		},
		ImagePullSecrets: []nameRef{{Name: imagePullSecret}},
		ServiceAccount: valuesServiceAccount{
			Create: false,
			Name:   serviceAccountName,
		},
		ContainerPort: containerPort,
		Service: valuesService{
			Enabled:    true,
			Type:       serviceType,
			Port:       servicePort,
			TargetPort: targetPort,
		},
		Resources:                    resourceProfileToValues(spec.Spec.Resources.Profile),
		Env:                          env,
		SecretEnv:                    secretEnv,
		AutomountServiceAccountToken: false,
		EnableServiceLinks:           false,
		ServiceMonitor: valuesServiceMonitor{
			Enabled: isEnabled(spec.Spec.Monitoring.Enabled),
			Path:    monitoringPath,
		},
	}

	if spec.Spec.Image.Digest != "" || isEnabled(spec.Spec.ImageAutomation.Enabled) {
		doc.Image.Digest = spec.Spec.Image.Digest
	}

	doc.Probes = valuesProbes{
		Enabled: true,
		Path:    healthPath,
		Startup: valuesProbeComponent{
			Enabled:             false,
			InitialDelaySeconds: 0,
			PeriodSeconds:       5,
			TimeoutSeconds:      2,
			FailureThreshold:    24,
		},
		Readiness: valuesProbeComponent{
			Enabled:             true,
			InitialDelaySeconds: 5,
			PeriodSeconds:       10,
			TimeoutSeconds:      2,
			FailureThreshold:    6,
		},
		Liveness: valuesProbeComponent{
			Enabled:             true,
			InitialDelaySeconds: 10,
			PeriodSeconds:       20,
			TimeoutSeconds:      2,
			FailureThreshold:    6,
		},
	}

	if isEnabled(spec.Spec.Route.Enabled) {
		doc.HTTPRoute = &valuesHTTPRoute{
			Enabled:   true,
			Hostnames: []string{spec.Spec.Route.Host},
			ParentRefs: []valuesHTTPRouteRef{
				{Name: "homelab-gateway", Namespace: "ingress", SectionName: "https"},
			},
			Rules: []valuesHTTPRouteRule{
				{
					Matches: []valuesHTTPRouteMatch{
						{
							Path: valuesHTTPRoutePath{
								Type:  "PathPrefix",
								Value: defaultString(spec.Spec.Route.Path, "/"),
							},
						},
					},
				},
			},
		}
	}

	return doc
}

func resourceProfileToValues(profile string) valuesResources {
	switch defaultString(profile, "small") {
	case "tiny":
		return valuesResources{
			Requests: valuesResourceUnits{CPU: "10m", Memory: "64Mi"},
			Limits:   valuesResourceUnits{Memory: "256Mi"},
		}
	case "medium":
		return valuesResources{
			Requests: valuesResourceUnits{CPU: "200m", Memory: "256Mi"},
			Limits:   valuesResourceUnits{CPU: "1000m", Memory: "1Gi"},
		}
	case "large":
		return valuesResources{
			Requests: valuesResourceUnits{CPU: "500m", Memory: "512Mi"},
			Limits:   valuesResourceUnits{CPU: "2000m", Memory: "2Gi"},
		}
	default:
		return valuesResources{
			Requests: valuesResourceUnits{CPU: "50m", Memory: "128Mi"},
			Limits:   valuesResourceUnits{Memory: "512Mi"},
		}
	}
}

func marshalYAMLWithIndent(v any, indent int) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(indent)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
