apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-13-game-engine
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/homelab/13-game-engine
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
