apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-proxy-robot
  namespace: demo
spec:
  type: kv-v2
  mount: kv
  path: harbor/robots/demo-pull
  refreshAfter: 1h
  hmacSecretData: true
  vaultAuthRef: vso-demo
  destination:
    name: harbor-proxy-robot
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
