apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-pull
  namespace: game-engine
spec:
  type: kv-v2
  mount: kv
  path: harbor/robots/game-engine-pull
  refreshAfter: 1h
  vaultAuthRef: vso-game-engine
  destination:
    name: harbor-pull
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson
